// Code generated by "go generate gonum.org/v1/gonum/blas/gonum”; DO NOT EDIT.

// Copyright ©2015 The Gonum Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package gonum

import (
	"gonum.org/v1/gonum/internal/asm/f32"
)

// Sdsdot computes the dot product of the two vectors plus a constant
//
//	alpha + \sum_i x[i]*y[i]
//
// Products and sums are evaluated in float64 precision. The order of summation
// is unspecified. Alpha is added before the final conversion to float32.
// If n is zero, Sdsdot returns alpha.
func (Implementation) Sdsdot(n int, alpha float32, x []float32, incX int, y []float32, incY int) float32 {
	if incX == 0 {
		panic(zeroIncX)
	}
	if incY == 0 {
		panic(zeroIncY)
	}
	if n <= 0 {
		if n == 0 {
			return alpha
		}
		panic(nLT0)
	}
	if incX == 1 && incY == 1 {
		if len(x) < n {
			panic(shortX)
		}
		if len(y) < n {
			panic(shortY)
		}
		return float32(float64(alpha) + f32.DdotUnitary(x[:n], y[:n]))
	}
	ix, ok := checkedDotStart(n, incX, len(x))
	if !ok {
		panic(shortX)
	}
	iy, ok := checkedDotStart(n, incY, len(y))
	if !ok {
		panic(shortY)
	}
	return float32(float64(alpha) + f32.DdotInc(x, y, uintptr(n), uintptr(incX), uintptr(incY), uintptr(ix), uintptr(iy)))
}
